FROM node:6.9

RUN npm install -g elm && elm package install -y

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

COPY package.json /src/package.json
RUN cd /src; npm install --silent --no-perm

COPY . /src

WORKDIR /src

CMD ["sh", "-c", "npm start"]