version: '2'
services:

  node_graphal_app:
    image: node:6.9-alpine
    container_name: node_graphal_app
    hostname: nodejs_app
    env_file: ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
      - ./client/dist:/src/public
    working_dir: /src
    command: ["sh", "-c", "npm install --no-perm --silent && npm start"]
    links:
      - mysql

  elm_app:
    build: ./client
    container_name: elm_app
    hostname: elm_app
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./client:/src
    working_dir: /src
    command: ["sh", "-c", "npm install --no-perm --silent && npm start"]
    env_file: ./client/.env

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=sample"
    volumes:
      - "./docker/var/lib/mysql:/var/lib/mysql"
