version: '2'
services:

  nodejs_app:
    build: ./server
    container_name: nodejs_app
    hostname: nodejs_app
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
      - /src/node_modules
      - ./client/dist:/src/public
    env_file: ./server/.env
    links:
      - mysql
      
  elm_app:
    build: ./client
    container_name: elm_app
    hostname: elm_app
    ports:
      - "3030:3030"
    volumes:
      - ./client:/src
      - /src/node_modules
    env_file: ./client/.env
    
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=sample"
    volumes:
      - "./docker/var/lib/mysql:/var/lib/mysql"
      - "./docker/etc/mysql/conf.d:/etc/mysql/conf.d"
